apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ramalama-gpt-oss-20b
  annotations:
    argocd.argoproj.io/sync-wave: "1"

resources:
- ../base-model

namePrefix: "gpt-oss-20b-"

commonLabels:
  app.kubernetes.io/instance: "gpt-oss-20b"
  model: "gpt-oss-20b"

configMapGenerator:
- name: model-config
  behavior: replace
  literals:
  - MODEL_NAME=gpt-oss-20b
  - MODEL_FILE=/mnt/models/gpt-oss-20b-UD-Q4_K_XL.gguf/gpt-oss-20b-UD-Q4_K_XL.gguf
  - ALIAS=gpt-oss-20b-model
- name: ramalama-config
  behavior: merge
  literals:
  - CTX_SIZE=20048
  - THREADS=-1
  - TEMP=1.0
  - TOP_K=0
  - TOP_P=1.0
  - CACHE_REUSE=256

images:
- name: MODEL_IMAGE
  newName: "ghcr.io/kush-gupt/gpt-oss-20b-ramalama"
  newTag: latest