apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: openshift-lightspeed-qwen3-30b-a3b-instruct-2507
  annotations:
    argocd.argoproj.io/sync-wave: "2"

resources:
  - ../../base/operator-only
  - olsconfig.yaml

patches:
  - target:
      kind: Secret
      name: credentials
    patch: |-
      - op: add
        path: /metadata/labels/model
        value: qwen3-30b-a3b-instruct-2507
      - op: add
        path: /metadata/labels/environment
        value: qwen3-30b-a3b-instruct-2507
  - target:
      kind: Subscription
      name: lightspeed-operator
    patch: |-
      - op: add
        path: /metadata/labels/model
        value: qwen3-30b-a3b-instruct-2507
      - op: add
        path: /metadata/labels/environment
        value: qwen3-30b-a3b-instruct-2507 