apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: openshift-lightspeed
  labels:
    app.kubernetes.io/name: ramalama-credentials
    app.kubernetes.io/part-of: openshift-lightspeed
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  apitoken: "dummy-token-for-local-ramalama"