# DEPRECATED: This file is deprecated in favor of k8s/lightspeed/base/credentials-secret.yaml
# This file is kept for backward compatibility but should not be used
# Use the GitOps-compatible configuration in k8s/lightspeed/ instead

apiVersion: v1
kind: Secret
metadata:
  name: credentials-legacy
  namespace: openshift-lightspeed
  labels:
    deprecated: "true"
    app.kubernetes.io/name: credentials-legacy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    description: "Legacy secret - use k8s/lightspeed/base/credentials-secret.yaml instead"
type: Opaque
stringData:
  apitoken: IGNORE