apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  labels:
    app.kubernetes.io/created-by: lightspeed-operator
    app.kubernetes.io/instance: olsconfig-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: olsconfig
    app.kubernetes.io/part-of: lightspeed-operator
spec:
  llm:
    providers:
      - credentialsSecretRef:
          name: credentials
        models:
          - name: default
        name: ramalama
        type: rhoai_vllm
        url: http://ramalama-qwen-service.ramalama.svc.cluster.local:8080/v1
  ols:
    logLevel: INFO
    defaultProvider: ramalama
    defaultModel: default
    deployment:
      console:
        replicas: 1
      replicas: 1
    conversationCache:
      postgres:
        credentialsSecret: lightspeed-postgres-secret
        dbName: postgres
        maxConnections: 2000
        sharedBuffers: 256MB
        user: postgres
      type: postgres
  olsDataCollector:
    logLevel: INFO