apiVersion: v1
kind: Service
metadata:
  name: ramalama-qwen-service
  labels:
    app: ramalama-qwen-3
spec:
  selector:
    app: ramalama-qwen-3
  ports:
    - name: http-api
      protocol: TCP
      port: 8080
      targetPort: 8080