apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-lightspeed-models
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: openshift-lightspeed
    app.kubernetes.io/part-of: ramalama-k8s
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
  # Model generator - discovers lightspeed overlays from git directory structure
  - git:
      repoURL: https://github.com/kush-gupt/ramalama-k8s.git
      revision: HEAD
      directories:
      - path: k8s/lightspeed/overlays/*
            
  template:
    metadata:
      name: 'openshift-lightspeed-{{path.basename}}'
      namespace: openshift-gitops
      labels:
        app.kubernetes.io/name: openshift-lightspeed
        app.kubernetes.io/component: ai-assistant
        app.kubernetes.io/instance: '{{path.basename}}'
        model: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
        
    spec:
      project: default
      
      source:
        repoURL: https://github.com/kush-gupt/ramalama-k8s.git
        targetRevision: HEAD
        path: '{{path}}'
          
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-lightspeed
        
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
            
      revisionHistoryLimit: 10
      
      # Health check configuration
      ignoreDifferences:
      - group: ols.openshift.io
        kind: OLSConfig
        jsonPointers:
        - /spec/llm/providers/0/url
      - group: ""
        kind: Secret
        jsonPointers:
        - /data
      - group: "project.openshift.io"
        kind: Project
        jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        
      info:
      - name: 'Component:'
        value: 'OpenShift Lightspeed'
      - name: 'Model:'
        value: '{{path.basename}}'
      - name: 'Generated By:'
        value: 'ApplicationSet' 