apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ramalama-base-model
  annotations:
    argocd.argoproj.io/sync-wave: "1"

namespace: ramalama

resources:
  - ../../base
  - deployment.yaml

commonLabels:
  app.kubernetes.io/component: llm-server

# Model-specific configuration
configMapGenerator:
  - name: model-config
    literals:
      - MODEL_NAME=base-model
      - MODEL_FILE=/mnt/models/model.file
      - ALIAS=base-model

# Apply deployment patches
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: ramalama-deployment 