ARG BASE_IMAGE_NAME
#="quay.io/kugupta/centos-ramalama-min:latest"
ARG MODEL_SOURCE_NAME
# = "quay.io/kugupta/qwen3-4b:latest"
FROM ${BASE_IMAGE_NAME}

ARG MODEL_SOURCE_NAME

# Copy the entire /models directory from the model source
# into the final application image.
# COPY --from=quay.io/kugupta/qwen3-4b:latest /models /models
COPY --from=${MODEL_SOURCE_NAME} /models /models

# This is a sanity check for OpenShift's random user ID.
USER root
RUN chmod -R a+rX /models
USER 1001

# Optional: Add labels to describe your new all-in-one image
LABEL maintainer="Kush Gupta"
LABEL description="All-in-one Ramalama server with embedded Qwen-4B Q4_K_M.gguf Unsloth model."