apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ramalama-production
  annotations:
    argocd.argoproj.io/sync-wave: "0"

namespace: ramalama-production

resources:
  - ../../base
  - namespace.yaml

labels:
  - includeSelectors: true
    pairs:
      environment: production
      version: stable

commonAnnotations:
  argocd.argoproj.io/sync-options: CreateNamespace=true

# Production-specific configuration
configMapGenerator:
  - name: ramalama-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - THREADS=16
      - CTX_SIZE=8192
      - CACHE_REUSE=512

# Production resource limits and security
patches:
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: ramalama-deployment

# Production-specific image tags
images:
  - name: MODEL_IMAGE
    newTag: stable

replicas:
  - name: ramalama-deployment
    count: 1