apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: ramalama
  labels:
    name: ramalama
    environment: production
    app.kubernetes.io/name: ramalama
    app.kubernetes.io/part-of: ramalama-k8s
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 