apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ramalama-deepseek-r1-qwen3-8b
  annotations:
    argocd.argoproj.io/sync-wave: "1"

resources:
  - ../base-model

namePrefix: deepseek-r1-qwen3-8b-

commonLabels:
  app.kubernetes.io/instance: deepseek-r1-qwen3-8b
  model: deepseek-r1-qwen3-8b

# Model-specific configuration
configMapGenerator:
  - name: model-config
    behavior: replace
    literals:
      - MODEL_NAME=DeepSeek R1 Qwen3 8B
      - MODEL_FILE=/mnt/models/DeepSeek-R1-0528-Qwen3-8B-UD-Q4_K_XL.gguf/DeepSeek-R1-0528-Qwen3-8B-UD-Q4_K_XL.gguf
      - ALIAS=deepseek-r1-qwen3-8b-model
  - name: ramalama-config
    behavior: merge
    literals:
      - CTX_SIZE=20048
      - THREADS=14
      - TEMP=0.6
      - TOP_K=20
      - TOP_P=0.95
      - CACHE_REUSE=256

# Model-specific image
images:
  - name: MODEL_IMAGE
    newName: ghcr.io/kush-gupt/deepseek-r1-qwen3-8b-ramalama
    newTag: latest

# Model-specific resource patches  
patches:
  - path: model-patch.yaml
    target:
      kind: Deployment
      name: ramalama-deployment