apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ramalama-base
  annotations:
    argocd.argoproj.io/sync-wave: "0"

resources:
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: ramalama
  app.kubernetes.io/part-of: ramalama-k8s
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  argocd.argoproj.io/managed: "true"

images:
  - name: MODEL_IMAGE
    newTag: latest

replicas:
  - name: ramalama-deployment
    count: 1

# Configuration for all models
configMapGenerator:
  - name: ramalama-config
    literals:
      - PORT=8080
      - HOST=0.0.0.0
      - LOG_COLORS=true
      - NO_WARMUP=true
      - JINJA=true
      - NGL=-1
      - MIN_P=0

# Base patches for all deployments
patchesStrategicMerge:
  - deployment-patch.yaml 