apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ramalama-dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"

namespace: ramalama-dev

resources:
  - ../../base
  - namespace.yaml

labels:
  - includeSelectors: true
    pairs:
      environment: dev
      version: latest

commonAnnotations:
  argocd.argoproj.io/sync-options: CreateNamespace=true

# Development-specific configuration
configMapGenerator:
  - name: ramalama-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - THREADS=4
      - CTX_SIZE=2048

# Development resource limits
patches:
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: ramalama-deployment

# Development-specific image tags
images:
  - name: MODEL_IMAGE
    newTag: dev-latest

replicas:
  - name: ramalama-deployment
    count: 1 